# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: termoo.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'termoo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctermoo.proto\x12\x06termoo\"2\n\x0ePalpiteRequest\x12\x0f\n\x07palavra\x18\x01 \x01(\t\x12\x0f\n\x07jogo_id\x18\x02 \x01(\t\"Y\n\x0fPalpiteResponse\x12\x12\n\nresultados\x18\x01 \x03(\t\x12\x0e\n\x06venceu\x18\x02 \x01(\x08\x12\x10\n\x08terminou\x18\x03 \x01(\x08\x12\x10\n\x08mensagem\x18\x04 \x01(\t\"\x11\n\x0fNovoJogoRequest\"X\n\x10NovoJogoResponse\x12\x0f\n\x07jogo_id\x18\x01 \x01(\t\x12\x1a\n\x12tentativas_maximas\x18\x02 \x01(\x05\x12\x17\n\x0ftamanho_palavra\x18\x03 \x01(\x05\x32\x90\x01\n\rTermooService\x12=\n\x08NovoJogo\x12\x17.termoo.NovoJogoRequest\x1a\x18.termoo.NovoJogoResponse\x12@\n\rEnviarPalpite\x12\x16.termoo.PalpiteRequest\x1a\x17.termoo.PalpiteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'termoo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PALPITEREQUEST']._serialized_start=24
  _globals['_PALPITEREQUEST']._serialized_end=74
  _globals['_PALPITERESPONSE']._serialized_start=76
  _globals['_PALPITERESPONSE']._serialized_end=165
  _globals['_NOVOJOGOREQUEST']._serialized_start=167
  _globals['_NOVOJOGOREQUEST']._serialized_end=184
  _globals['_NOVOJOGORESPONSE']._serialized_start=186
  _globals['_NOVOJOGORESPONSE']._serialized_end=274
  _globals['_TERMOOSERVICE']._serialized_start=277
  _globals['_TERMOOSERVICE']._serialized_end=421
# @@protoc_insertion_point(module_scope)
